# file: tools/copilot-agent-util-rust/.cargo/config.toml
# version: 1.1.0
# guid: b2c3d4e5-f6a7-8901-bcde-f23456789012

[build]
target-dir = "target"

[env]
RUST_BACKTRACE = "1"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"
