# file: .github/workflows/release.yml
# version: 1.0.0
# guid: c1d2e3f4-a5b6-7c8d-9e0f-1a2b3c4d5e6f

name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (auto, major, minor, patch)"
        required: false
        default: "auto"
        type: choice
        options:
          - auto
          - major
          - minor
          - patch
      prerelease:
        description: "Create as prerelease"
        required: false
        default: false
        type: boolean
      draft:
        description: "Create as draft"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/**"
      - "!.github/workflows/**"

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  detect-language:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.detection.outputs.language }}
      project-type: ${{ steps.detection.outputs.project-type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect project language
        id: detection
        run: |
          echo "Detecting project language..."

          if [[ -f "Cargo.toml" ]]; then
            echo "language=rust" >> $GITHUB_OUTPUT
            echo "project-type=rust" >> $GITHUB_OUTPUT
            echo "✅ Detected: Rust project (Cargo.toml found)"
          elif [[ -f "go.mod" ]]; then
            echo "language=go" >> $GITHUB_OUTPUT
            echo "project-type=go" >> $GITHUB_OUTPUT
            echo "✅ Detected: Go project (go.mod found)"
          elif [[ -f "package.json" && -f "tsconfig.json" ]]; then
            echo "language=typescript" >> $GITHUB_OUTPUT
            echo "project-type=typescript" >> $GITHUB_OUTPUT
            echo "✅ Detected: TypeScript project (package.json + tsconfig.json found)"
          elif [[ -f "package.json" ]]; then
            echo "language=javascript" >> $GITHUB_OUTPUT
            echo "project-type=javascript" >> $GITHUB_OUTPUT
            echo "✅ Detected: JavaScript project (package.json found)"
          elif [[ -f "pyproject.toml" || -f "setup.py" || -f "requirements.txt" ]]; then
            echo "language=python" >> $GITHUB_OUTPUT
            echo "project-type=python" >> $GITHUB_OUTPUT
            echo "✅ Detected: Python project"
          else
            echo "❌ Unknown project type - no supported language files found"
            echo "language=unknown" >> $GITHUB_OUTPUT
            echo "project-type=unknown" >> $GITHUB_OUTPUT
            exit 1
          fi

  release-rust:
    needs: detect-language
    if: needs.detect-language.outputs.language == 'rust'
    uses: ./.github/workflows/release-rust.yml
    with:
      release_type: ${{ inputs.release_type || 'auto' }}
      prerelease: ${{ inputs.prerelease || false }}
      draft: ${{ inputs.draft || false }}
    secrets: inherit

  release-go:
    needs: detect-language
    if: needs.detect-language.outputs.language == 'go'
    uses: ./.github/workflows/release-go.yml
    with:
      release_type: ${{ inputs.release_type || 'auto' }}
      prerelease: ${{ inputs.prerelease || false }}
      draft: ${{ inputs.draft || false }}
    secrets: inherit

  release-python:
    needs: detect-language
    if: needs.detect-language.outputs.language == 'python'
    uses: ./.github/workflows/release-python.yml
    with:
      release_type: ${{ inputs.release_type || 'auto' }}
      prerelease: ${{ inputs.prerelease || false }}
      draft: ${{ inputs.draft || false }}
    secrets: inherit

  release-javascript:
    needs: detect-language
    if: needs.detect-language.outputs.language == 'javascript'
    uses: ./.github/workflows/release-javascript.yml
    with:
      release_type: ${{ inputs.release_type || 'auto' }}
      prerelease: ${{ inputs.prerelease || false }}
      draft: ${{ inputs.draft || false }}
    secrets: inherit

  release-typescript:
    needs: detect-language
    if: needs.detect-language.outputs.language == 'typescript'
    uses: ./.github/workflows/release-typescript.yml
    with:
      release_type: ${{ inputs.release_type || 'auto' }}
      prerelease: ${{ inputs.prerelease || false }}
      draft: ${{ inputs.draft || false }}
    secrets: inherit

  summary:
    runs-on: ubuntu-latest
    needs: [detect-language, release-rust, release-go, release-python, release-javascript, release-typescript]
    if: always()
    steps:
      - name: Release Summary
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Language Detected:** ${{ needs.detect-language.outputs.language }}" >> $GITHUB_STEP_SUMMARY
          echo "**Project Type:** ${{ needs.detect-language.outputs.project-type }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.detect-language.outputs.language }}" == "rust" ]]; then
            echo "**Rust Release Status:** ${{ needs.release-rust.result }}" >> $GITHUB_STEP_SUMMARY
            if [[ "${{ needs.release-rust.outputs.version }}" != "" ]]; then
              echo "**Released Version:** ${{ needs.release-rust.outputs.version }}" >> $GITHUB_STEP_SUMMARY
              echo "**Release Tag:** ${{ needs.release-rust.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
            fi
          elif [[ "${{ needs.detect-language.outputs.language }}" == "go" ]]; then
            echo "**Go Release Status:** ${{ needs.release-go.result }}" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ needs.detect-language.outputs.language }}" == "python" ]]; then
            echo "**Python Release Status:** ${{ needs.release-python.result }}" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ needs.detect-language.outputs.language }}" == "javascript" ]]; then
            echo "**JavaScript Release Status:** ${{ needs.release-javascript.result }}" >> $GITHUB_STEP_SUMMARY
          elif [[ "${{ needs.detect-language.outputs.language }}" == "typescript" ]]; then
            echo "**TypeScript Release Status:** ${{ needs.release-typescript.result }}" >> $GITHUB_STEP_SUMMARY
          fi
